- src/Action/BaseAction.php
- src/Listener/ApiListener.php
- tests/TestCase/Action/AddActionTest.php
- tests/TestCase/Action/EditActionTest.php
``String`` Class has been replace by ``Text``
``validatePresence()`` has been renamed ``requirePresence()``
> update deprecated method

- src/Error/ExceptionRenderer.php
- tests/TestCase/Error/ExceptionRendererTest.php
Exception info should only be shown in debug mode.
> Hide exception details

- .scrutinizer.yml
- docs/_code/listener_example.php
> Fix scrutinizer issue

- src/Controller/Component/CrudComponent.php
- src/Core/ProxyTrait.php
- src/Listener/RelatedModelsListener.php
We previously were sending it an array.
> Properly call _trigger() with a Subject object

- src/Action/BaseAction.php
- src/Controller/Component/CrudComponent.php
- tests/TestCase/Action/AddActionTest.php
- tests/TestCase/Action/Bulk/DeleteActionTest.php
- tests/TestCase/Action/Bulk/SetValueActionTest.php
- tests/TestCase/Action/Bulk/ToggleActionTest.php
- tests/TestCase/Action/DeleteActionTest.php
- tests/TestCase/Action/EditActionTest.php
- tests/TestCase/Action/IndexActionTest.php
- tests/TestCase/Action/ViewActionTest.php
Updated event manager methods in the component.
> Replaced the deprecated EventManager methods

- docs/listeners/redirect.rst
Ref https://github.com/FriendsOfCake/crud/issues/257
> Docs for RedirectListener

- tests/App/Model/Table/CrudExamplesTable.php
This is my first pull request ever, so I hope I did a good job (process-wise). I've run the testcases and they succeed. Created seperate branch, to keep fixes seperate.
Let me know if this is correct.
> Solves 305-findunpublished query return

- src/Template/Bake/Controller/controller.ctp
Added a controller bake template.
> Resolves #286. 

- docs/configuration.rst
I havn't compiled this, so I don't know if it looks correct - otherwise I'm sure somebody could point me where to go :smile:
> Added section about disabling already loaded actions in a controller

- composer.json
- docs/listeners/api-pagination.rst
- docs/listeners/api-query-log.rst
- docs/listeners/api.rst
- docs/listeners/redirect.rst
- docs/listeners/search.rst
- docs/unit-testing.rst
- src/Listener/SearchListener.php
- tests/TestCase/Listener/SearchListenerTest.php
FOC/Search meets FOC/Crud.
An implementation of an additonal listener to play nicely with FOC/Search.
Test cases not done yet, comments are welcome.
EDIT:
Don't merge yet, the test case is incomplete.
> init search listener

- src/Action/Bulk/BaseAction.php
- tests/App/Controller/UsersController.php
- tests/App/Model/Entity/User.php
- tests/App/Model/Table/UsersTable.php
- tests/Fixture/UsersFixture.php
- tests/TestCase/Action/Bulk/DeleteActionTest.php
- tests/TestCase/Action/Bulk/SetValueActionTest.php
- tests/TestCase/Action/Bulk/ToggleActionTest.php
It's not possible to have a bulk delete for UUID based databases. This PR will fix it.
> uuid for bulk actions

- src/Listener/ApiPaginationListener.php
- tests/TestCase/Listener/ApiPaginationListenerTest.php
> Fix setting paging data for plugin models.

- src/Listener/RelatedModelsListener.php
- tests/TestCase/Listener/RelatedModelsListenerTest.php
> Contain related models in beforePaginate()

- src/Action/DeleteAction.php
- tests/TestCase/Action/DeleteActionTest.php
refs https://github.com/FriendsOfCake/crud/issues/338
> limit delete action methods

- src/Action/DeleteAction.php
- tests/TestCase/Action/DeleteActionTest.php
Reverts FriendsOfCake/crud#344
> Revert "limit delete action methods"

- src/Listener/ApiQueryLogListener.php
> Catch exception and ignore it in ApiQueryLogListener

- docs/_partials/events/after_lookup.rst
- docs/_partials/events/before_lookup.rst
- docs/actions/lookup.rst
> Add in related documentations for lookup actions

- examples/blog.md
using 'notBlank' instead of "notEmpty" since it is depcrecated since cake 2.7
> removed deprecated function

- docs/actions/index.rst
> Document `find_method` usage in IndexAction

- .travis.yml
- composer.json
- src/Error/Exception/ValidationException.php
- tests/TestCase/Action/AddActionTest.php
- tests/TestCase/Error/ExceptionRendererTest.php
- tests/TestCase/Listener/ApiListenerTest.php
This will need to wait for cakephp/cakephp#8237 before being merged.
Note: there will be unrelated errors that are happening on other PRs too. Tried quickly resolving, no luck. Any pointers welcomed.
> Switched validation error code, closes #337

- src/Traits/FindMethodTrait.php
I'm a little confused with tests in this repo. Any pointers as to where / how to test this case?
> Now possible to edit the query in view action via beforeFind()

- src/Controller/Component/CrudComponent.php
- tests/TestCase/Controller/Component/CrudComponentTest.php
> Fix CrudComponent::useModel().

- src/Action/LookupAction.php
@lorenzo Sorry totally forgot to adjust the other PR.
refs https://github.com/FriendsOfCake/crud/pull/390
> lookup fields should be inside schema

- docs/_partials/events/after_bulk.rst
- docs/_partials/events/after_delete.rst
- docs/_partials/events/after_find.rst
- docs/_partials/events/after_lookup.rst
- docs/_partials/events/after_paginate.rst
- docs/_partials/events/after_save.rst
- docs/_partials/events/before_bulk.rst
- docs/_partials/events/before_delete.rst
- docs/_partials/events/before_lookup.rst
- docs/_partials/events/set_flash.rst
- docs/configuration.rst
- docs/crud-subject.rst
- docs/events.rst
- docs/installation.rst
- docs/quick-start.rst
It's not very clear how to actually customise the flash messages, so I've just expanded upon the event docs a bit with some examples.
> Flash customisation

- docs/listeners/api.rst
- src/Listener/ApiListener.php
- tests/TestCase/Listener/ApiListenerTest.php
refs https://github.com/FriendsOfCake/crud/issues/407
> Adds config option for custom ExceptionRenderer class

- .semver
It's an unwanted chore updating it on each release which
is almost always forgotten.
> Remove .semver file.

- docs/listeners/api.rst
- src/Error/ExceptionRenderer.php
refs https://github.com/FriendsOfCake/crud/issues/337
> Update orphaned 412s

- docs/listeners/api-pagination.rst
The example API pagination configuration code was incorrect in the documentation.
> Fixed example code

- docs/listeners/api.rst
- src/Listener/ApiListener.php
- src/TestSuite/IntegrationTestCase.php
- tests/TestCase/Action/AddActionTest.php
- tests/TestCase/Action/BaseActionTest.php
- tests/TestCase/Action/Bulk/DeleteActionTest.php
- tests/TestCase/Action/Bulk/SetValueActionTest.php
- tests/TestCase/Action/Bulk/ToggleActionTest.php
- tests/TestCase/Action/DeleteActionTest.php
- tests/TestCase/Action/EditActionTest.php
- tests/TestCase/Action/IndexActionTest.php
- tests/TestCase/Action/LookupActionTest.php
- tests/TestCase/Action/ViewActionTest.php
- tests/TestCase/Controller/Component/CrudComponentTest.php
- tests/TestCase/Error/ExceptionRendererTest.php
- tests/TestCase/Listener/ApiListenerTest.php
> Account for new PSR7 middleware of Cake 3.3.

- src/Traits/FindMethodTrait.php
> Does not return and has no return value.

- tests/TestCase/Listener/ApiListenerTest.php
This fixes the currently failing test case
> Fix failing test

- src/Action/DeleteAction.php
Comes handy when using https://github.com/UseMuffin/trash for example.
```
$this->Crud->action()->config('deleteMethod', 'trash');
```
> Make delete method used configurable

- src/Action/AddAction.php
- src/Action/BaseAction.php
- src/Action/Bulk/BaseAction.php
- src/Action/Bulk/DeleteAction.php
- src/Action/Bulk/SetValueAction.php
- src/Action/Bulk/ToggleAction.php
- src/Action/DeleteAction.php
- src/Action/EditAction.php
- src/Action/ViewAction.php
- src/Controller/Component/CrudComponent.php
- src/Controller/ControllerTrait.php
- src/Core/ProxyTrait.php
- src/Error/ExceptionRenderer.php
- src/Listener/ApiListener.php
- src/Listener/ApiPaginationListener.php
- src/Listener/ApiQueryLogListener.php
- src/Listener/BaseListener.php
- src/Listener/RelatedModelsListener.php
- src/TestSuite/Traits/CrudTestTrait.php
- src/Traits/FindMethodTrait.php
- src/Traits/RedirectTrait.php
- src/Traits/SerializeTrait.php
- src/Traits/ViewVarTrait.php
Some things are not yet fixed:
- "mixed" is used a lot where it could be more concrete probably (string|null etc)
But this already cleans it up quite a bit. Less red/yellow in IDE (phpstorm) as well.
> Fix doc blocks and return value.

- src/View/JsonApiView.php
This PR adds the "custom dynamic schema" functionality as described in the docs.
> Make JsonApiListener use schemas as described in the docs

- docs/listeners/api.rst
- docs/listeners/jsonapi.rst
> JsonApiListener documentation

- docs/crud-subject.rst
"Crud's" needs an apostrophe since it's possessive
> Add needed apostrophe

- src/Action/AddAction.php
- tests/TestCase/Action/AddActionTest.php
This PR adds the possibility to stop propagation for the `add` action which is useful when one requires POST data to be handled by Crud but does not want to create an accompanying database record. 
This is a common requirement for JSON API situations where we MUST use CRUD for everything, even when we do not want/need to create database records. An example:
- Crud JsonApiListener handles JWT authentication
- frontend must POST authentication data to the API
- there is no need for storing the JWT token (and we thus stop propagation)
- we only present the jwt token as JSON API to the frontend for further handling
> Adds propagation stop to add action

- docs/listeners/jsonapi.rst
Give users fair notice of missing features.
> Adds JsonApiListener disclaimer

- docs/_partials/events/after_bulk.rst
- docs/_partials/events/after_delete.rst
- docs/_partials/events/after_find.rst
- docs/_partials/events/after_lookup.rst
- docs/_partials/events/after_paginate.rst
- docs/_partials/events/after_save.rst
- docs/_partials/events/before_bulk.rst
- docs/_partials/events/before_delete.rst
- docs/_partials/events/before_find.rst
- docs/_partials/events/set_flash.rst
- docs/crud-subject.rst
- docs/listeners/api-pagination.rst
- docs/listeners/api.rst
- docs/listeners/jsonapi.rst
- docs/listeners/related-models.rst
- added some clarifications to the error renderer setting with 3.3+
-  replace depricated $event->subject() with $event->getSubject()
> doc: fixes

- docs/api.rst
- docs/listeners/jsonapi.rst
Plus some auto indentation corrections.
> Consistent use of JSON API in documentation

- src/Listener/ApiListener.php
- tests/TestCase/Action/AddActionTest.php
- tests/TestCase/Listener/ApiListenerTest.php
> _checkRequestMethods should throw MethodNotAllowedException

- docs/actions/custom.rst
Recently I struggled a bit on how to use custom named controller actions in CRUD context. It seems pretty selfexplaintory, but took me a while to get that. Beacuase of that I propose this document improvement, as other readers might also have this problem.
Thank you!
Sebastian Köller
> Custom named controller actions

- docs/Dockerfile
Minor correction: cakephp/docs -> crud/docs
> Minor correction to docs Dockerfile

- docs/_partials/events/set_flash.rst
As required by https://github.com/FriendsOfCake/crud/issues/554#issuecomment-339546743
> Fix alert-dismissible being ignored by bootstrap-ui

- docs/_partials/events/before_delete.rst
> Corrected beforeDelete docs

- src/Action/Bulk/BaseAction.php
- src/Action/IndexAction.php
- src/Action/LookupAction.php
- src/Traits/FindMethodTrait.php
- tests/TestCase/Action/Bulk/SetValueActionTest.php
- tests/TestCase/Action/IndexActionTest.php
- tests/TestCase/Action/LookupActionTest.php
> Allow all actions to use custom finder with options.

- src/Action/BaseAction.php
- src/Action/EditAction.php
- src/Controller/Component/CrudComponent.php
- src/Core/ProxyTrait.php
- src/Error/ExceptionRenderer.php
- src/Listener/ApiListener.php
- src/Listener/RedirectListener.php
- src/Listener/SearchListener.php
- src/Traits/FindMethodTrait.php
- src/Traits/ViewVarTrait.php
I've used PHP Storms automated tools to check for the docblocks which need some love. There seem to be a few.
I can't find any more code deprecations!
> 3.4 - Fixed doc blocks

- phpstan.neon
- src/Listener/SearchListener.php
Closes #578.
@itodor Can you confirm this fixes your problem?
> Fix compatibility with older version of search plugin.

- Controller/Crud/CrudBaseObject.php
- composer.json
> Extend CakeObject instead of Object

- src/Action/AddAction.php
- src/Action/BaseAction.php
- src/Action/Bulk/BaseAction.php
- src/Action/EditAction.php
- src/Controller/Component/CrudComponent.php
- src/Core/ProxyTrait.php
- src/Listener/ApiListener.php
- tests/TestCase/Action/BaseActionTest.php
- tests/TestCase/Controller/Component/CrudComponentTest.php
> Update namespace for deprecated exception classes.

- aliases.php
Refs : https://github.com/FriendsOfCake/crud/pull/595
> add alias for 'NotFoundException'

- .stickler.yml
- docs/listeners/api-query-log.rst
- src/Action/BaseAction.php
- src/Controller/ControllerTrait.php
- src/Error/Exception/CrudException.php
- src/Event/Subject.php
- src/Listener/ApiQueryLogListener.php
- src/Template/Bake/Controller/controller.ctp
- tests/App/Model/Entity/Blog.php
- tests/App/Model/Entity/User.php
- tests/App/Model/Table/BlogsTable.php
- tests/App/Model/Table/CrudExamplesTable.php
- tests/App/Model/Table/UsersTable.php
- tests/App/Template/Blogs/view.ctp
- tests/TestCase/Action/AddActionTest.php
- tests/TestCase/Action/BaseActionTest.php
- tests/TestCase/Action/Bulk/DeleteActionTest.php
- tests/TestCase/Action/Bulk/SetValueActionTest.php
- tests/TestCase/Action/Bulk/ToggleActionTest.php
- tests/TestCase/Action/DeleteActionTest.php
- tests/TestCase/Action/EditActionTest.php
- tests/TestCase/Controller/Component/CrudComponentTest.php
- tests/TestCase/Error/ExceptionRendererTest.php
- tests/TestCase/Listener/ApiListenerTest.php
- tests/TestCase/Listener/ApiPaginationListenerTest.php
- tests/TestCase/Listener/ApiQueryLogListenerTest.php
- tests/TestCase/Listener/RedirectListenerTest.php
- tests/TestCase/Listener/RelatedModelsListenerTest.php
- tests/TestCase/Listener/SearchListenerTest.php
- tests/bootstrap.php
Fixes #632
Backport to v5/master.
> Adds option to control which connections to log (backport to v5/master)

- tests/TestCase/Listener/ApiListenerTest.php
> Add test showing deleting failure results in 400 response.

- templates/bake/Controller/controller.twig
> Fix bake template.

- .github/workflows/ci.yml
- tests/TestCase/Error/ExceptionRendererTest.php
The Cake core's exception name has changed in 4.2.
> Fix tests.

- src/Listener/ApiListener.php
- tests/TestCase/Listener/ApiListenerTest.php
> Update request type detectors for CakePHP 4.4

- src/Controller/ControllerTrait.php
`Controller` already has `viewClass()` method.
> Remove unneeded method override.

- src/Error/ExceptionRenderer.php
> Update method signature to match parent class' method.

- docs/listeners/api-pagination.rst
- docs/listeners/api-query-log.rst
- docs/listeners/api.rst
- docs/quick-start.rst
- src/Listener/ApiListener.php
> Fix ApiListener docs

- src/Action/AddAction.php
- src/Action/EditAction.php
Handle "beforeSave" event being stopped for EditAction.
> Sync add/edit actions.

- docs/listeners/custom.rst
- tests/test_app/src/Model/Table/BlogsTable.php
- tests/test_app/src/Model/Table/CrudExamplesTable.php
Resolves https://github.com/FriendsOfCake/crud/issues/764
> Fix up SelectQuery examples.
