FriendsOfCake/crud

src/Action/AddAction.php, src/Core/ProxyTrait.php
Due to the change on the validation layer in CakePHP, validation errors are shown on a empty GET request.
=> 3.0 - Update add action to prevent showing validation errors on GET request.

src/Error/ExceptionRenderer.php, src/Listener/ApiListener.php, tests/TestCase/Listener/ApiListenerTest.php
As it was, the `ExceptionRenderer` was not being registered by the listener
and the `Cake\Network\Response` was not properly returned on validation
exception rendering.
=> Fix API exception rendering

src/Listener/RelatedModelsListener.php, tests/TestCase/Listener/RelatedModelsListenerTest.php
The type for belongsToMany is manyToMany, so RelatedModel didn't fetch associated models with belongsToMany association.
https://github.com/cakephp/cakephp/blob/master/src/ORM/Association.php#L78
=> Fix RelatedModel association types

docs/_partials/events/after_bulk.rst, docs/_partials/events/before_bulk.rst, docs/actions.rst, docs/actions/bulk-delete.rst, docs/actions/bulk-set-value.rst, docs/actions/bulk-toggle.rst, docs/actions/bulk.rst, src/Action/Bulk/BaseAction.php, src/Action/Bulk/DeleteAction.php, src/Action/Bulk/SetValueAction.php, src/Action/Bulk/ToggleAction.php, src/Action/BulkAction.php, src/Action/IndexAction.php, tests/App/Controller/BlogsController.php, tests/TestCase/Action/Bulk/DeleteActionTest.php, tests/TestCase/Action/Bulk/SetValueActionTest.php, tests/TestCase/Action/Bulk/ToggleActionTest.php
This will allow us to implement `_bulk` handlers for actions that occur from `index`-like pages. Any subclass that implements a `_bulk` method will be given a $query object that can be used to reference a set of database objects. The classes can then do whatever they like - such as publish all posts, or delete records.
This sort of method is more useful for admin modules than for apis, but is a common task in application development
=> Initial pass at a BulkAction base handler

src/Listener/RelatedModelsListener.php, tests/TestCase/Listener/RelatedModelsListenerTest.php
Related models used association name as the key for associations. This value is lowercase model name without underscores, like it's set in associations. I changed it so it uses the association's name, this way it's a proper camel cased model name.
=> Use associationClass name instead of association

src/Action/IndexAction.php, src/Action/LookupAction.php, tests/App/Controller/BlogsController.php, tests/TestCase/Action/IndexActionTest.php, tests/TestCase/Action/LookupActionTest.php
This PR includes the following changes:
* Allows `beforePaginate` to alter the query before it is executed
* Fixes warning in LookupAction
* Adds the ability to alter the query in LookupAction
=> Improvements and fixes

src/Action/AddAction.php
When displaying an add form and sending some of the fields in the query string,
it is better to not pre-validate the full form as it will obviously contain errors.
=> Fixed issue caused by validation of query string

src/Listener/RelatedModelsListener.php
Borrows same exception/message from core as a more helpful alternative to:
Fatal error: Call to a member function name() on null
=> Throw exception when 'relatedModels' association not found

docs/listeners/related-models.rst
Before the docs improvement it's not clear that the listener needs to be loaded. It sounds like that `relatedModels` will work without any additional configuration. Especially because the following explanation:
```
By default all related model lists for main CRUD table instance will be fetched, but only for add, edit and corresponding admin actions.
```
=> related-models docs

Controller/Crud/CrudAction.php
Following line causes "Fatal Error: Class 'String' not found" in CakePHP 2.7.x
https://github.com/FriendsOfCake/crud/blob/3.0/Controller/Crud/CrudAction.php#L239
This patch fixes the problem
=> Fix for "Fatal Error: Class 'String' not found" in CakePHP 2.7.x

docs/_partials/events/after_find.rst
I use the latest crud plugin but all $event->subject->item doesn't exist. But $event->subject->entity does. Is it a mispell in docs? Or forgoten to be updated?
=> Isit forgoten to be updated?

src/Listener/ApiListener.php, tests/TestCase/Listener/ApiListenerTest.php
In general I agree that flash messages are not necessary for api requests. Let me explain with the following use case why an optional flash message may be useful.
I want to use `deleteAll` in a normal cake template context. Regarding issues with `<form>` in `<form>` I decided to execute `deleteAll` with an AJAX request. Therefore I loaded the API listener to get a well-formed response for my AJAX request. Now I want to refresh my page in jQuery's `success` callback and want to show a flash message to the user after the reload is done.
What do you think?
EDIT:
As usual, test cases follow after you're fine with the changes itself.
=> optional flash messages

composer.json, src/Listener/ApiListener.php, tests/TestCase/Listener/ApiListenerTest.php
refs http://book.cakephp.org/3.0/en/appendices/3-1-migration-guide.html#requesthandlercomponent
Has anyone an idea why the other test cases fail? It should be working like before without to change the test cases.
=> deprecated method viewClassMap

src/Error/ExceptionRenderer.php, tests/TestCase/Error/ExceptionRendererTest.php
Set trace info in response only if not already added by
core's ExceptionRenderer::render()
=> Simplify ExceptionRenderer::_outputMessage()

src/Action/DeleteAction.php, tests/TestCase/Action/DeleteActionTest.php
In the of the discussion in the previous revert, namely that the cakephp 3 version introduced a regression compared to cake 2 and that the current handler is by default exploitable by trivial attack CSRF vectors, I'm bringing back the code that was reverted.
=> Bringing back "limit delete action methods"

docs/_partials/events/after_save.rst
The `afterSave()` event documentation indicates that `item` is one of the keys of the event `subject()`.  This is incorrect.  The correct name of the key is `entity`.  This PR makes the necessary correction to the documentation.
=> Corrects incorrect afterSave() subject key name

src/Action/DeleteAction.php, tests/App/Template/Blogs/delete.ctp
Hey,
This missing return statement makes the Response to be null so no redirect is made.
I couldn't figure out how the tests are passing for `delete` method.
Best,
Pedro.
=> adding the missing return

docs/listeners/api.rst
Splits POST and PUT actions as they respond differently, also removes:
- note about HTTP header (with link to /view) being sent after succesful POST
- mention of 301 code for POST (since it does not seem to be used)
=> Splits POST and PUT actions

src/Action/IndexAction.php
This enables us to treat the IndexAction exactly as we treat any other action in regards to custom finds.
=> Add the ability to customize the findMethod in IndexAction

src/Listener/SearchListener.php
Rather than throw the following error/exception:
```
Unknown method "filterParams"
```
We throw a RuntimeException that informs the developer that they have misconfigured their application, allowing them to more quickly debug the issue.
=> Throw a more user-friendly exception when the SearchBehavior is not attached

src/Listener/SearchListener.php
- The method exists on a behavior, and is proxied, so therefore `method_exists` is a bad check.
- You can't simply check for `hasBehavior('Search')` as a user can alias a behavior to another one.
- Since we are calling `filterParams` and that is the only dependency, simply checking if the method is in the `BehaviorRegistry::$methodMap` is enough.
=> Fix check for missing behavior

.travis.yml
Solves [failing coveralls build](https://travis-ci.org/FriendsOfCake/crud/jobs/99232151) due to requirement changing from 5.4 to 5.5.
=> Use php5.5 for coveralls

docs/_partials/events/before_redirect.rst, docs/_partials/events/set_flash.rst
The documentation incorrectly indicated that a key named `item` was available as part of the event subject for the `beforeRedirect` and `setFlash` events.  The correct name for the key is `entity`.  This PR corrects the documentation.
=> Fix incorrect subject key name in docs

docs/listeners/api-pagination.rst, docs/listeners/redirect.rst, docs/listeners/related-models.rst
- adds pagination listener configuration example (for new users)
- fixes wrong class in pagination `AppController` example
- adds missing event for all `beforeFilter()` examples (all docs)
=> Adds pagination configuration example

src/Core/ProxyTrait.php
Right now, if one defines a default factory the cake promoted way using `ModelAwareTrait::modelType()`, the plugin doesn't automatically detect it.
This change will fix the behavior and help avoiding to set the factory twice (for controller and for Crud's proxy).
=> Fallback to default factory for controller

docs/conf.py
* Updated the copyright year, pending #395 
* Include the `sphinxcontrib.phpdomain` to make local highlighting easier `sudo easy_install -U sphinxcontrib-phpdomain`
* Added a description for the plugin
* Added the relevant lexers for PHP
* Excluded all the partials, so you don't get a warning about them not being in the toctree when building the docs
=> Updated Sphinx config to include pygments for phpinline

docs/configuration.rst
Added a new section to the Configuration page to give an example of how to enable Crud for just a single routing prefix.
Also fixed some minor indenting.
=> Resolves #393

docs/listeners/api.rst
A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
=> remove Bad Apostrophe

docs/events.rst, docs/installation.rst, docs/listeners/related-models.rst
Hopefully this goes some way towards resolving the confusion about what the exact functionality of the listener is. It seems that the name of the listener gives people some expectations about it's functionality which it does not fulfill.
I've tried to clarify how it behaves when used with an `index` action as well it's primary usage for creating list data for `add` and `edit` methods.
=> Resolves #404

src/Action/LookupAction.php
Before:
Call on `/products/lookup.json?id=3` prdocued:
After:
Call on `/products/lookup.json?id=3` produces:
=> idField should be in list of columns

src/Action/Bulk/BaseAction.php, tests/TestCase/Action/Bulk/SetValueActionTest.php, tests/TestCase/Listener/ApiListenerTest.php
I noticed that when executing bulk actions, they were being performed on the wrong entries since _processIds() was using array_keys() to extract the ids from the array's keys, when it should be using the array's values.
Example:
> POST /network-objects/bulk/updating '{"id":[3,4]}'
This would update the object with id 1, instead of objects 3 and 4.
=> Properly handle ids during bulk actions

src/Listener/ApiListener.php
I need to render templates for specific API actions. Therefore I set `_serialize` to false in `Crud.beforeRender`. If I keep the deleted lines, it will search for templates inside `Posts/json/json/view.ctp` instead of `Posts/json/view.ctp`.
=> remove unnecessary renderAs()

docs/listeners/api.rst
It's possible to customise the data that is returned with a add action for the API listener. However, how to do this is not currently documented. This documents it.
=> Add an example on how to change API return data

docs/listeners/related-models.rst, src/Listener/RelatedModelsListener.php
- `keyField` will now using the relation `bindingKey` instead of the `primaryKey` by default in `find('list')`
- `entity` are a new `subject` key for `view` and `edit` - and will contain the current `entity` you are finding relations for - this allow for injection of related model conditions based on the `entity` properties ( e.g. an `entity` with `country_id = 1` - you can now easily limit relations to known good relations for that country id
=> relatedModel improvements

docs/actions/custom.rst
The name of the action was different to the `className` used in the example usage further down the page.
=> Fixed name of custom action in documentation

docs/actions/bulk.rst
The example code shows the `_execute()` method rather than the `bulk()` one (I assume this is incorrect based on the plugin's code and the paragraph before the example.
=> Fixed bulk action example code

Controller/Crud/CrudBaseObject.php
=> Load base Object class explicitly because Cake no longer does.

src/Listener/JsonApiListener.php, src/Schema/JsonApi/DynamicEntitySchema.php, src/Traits/JsonApiTrait.php, src/View/JsonApiView.php, tests/TestCase/Listener/JsonApiListenerTest.php, tests/TestCase/Schema/DynamicEntitySchemaTest.php, tests/TestCase/Traits/JsonApiTraitTest.php, tests/TestCase/View/JsonApiViewTest.php
This replaces the seriously flawed link generating logic (previously breaking a lot of things) with CakePHP Router generated links. This PR solves most of the concerns I had before. Now:
- respects prefixes
- respects dasherized routes, etc
- respects CakePHP `base` configuration option
Added an option to switch between absolute and relative links as a new year's bonus.
=> Use CakePHP Router to generate JSONAPI links

src/Listener/JsonApiListener.php, tests/TestCase/Listener/JsonApiListenerTest.php
While writing the docs I realized the listener was not unobtrusive. With this PR absolutely nothing is done by the listener unless the `application/vnd.api+json` Accept Header is used.
=> Make JsonApiListener unobtrusive as described in the docs

src/Listener/ApiPaginationListener.php, tests/TestCase/Listener/ApiPaginationListenerTest.php
This is the last PR on my list and fixes the pagination links by generating them using CakePHP Router instead of lame hackery (was forgotten in #467).
=> Use Cake Router to generate JSON API pagination links

docs/listeners/jsonapi.rst, src/Listener/JsonApiListener.php, src/View/JsonApiView.php, tests/TestCase/Listener/JsonApiListenerTest.php, tests/TestCase/View/JsonApiViewTest.php
Changes the type of the `meta` configuration option from **mixed** to **array** as commented by @jippi.
=> Changes jsonapi configuration option 'meta' to array type

docs/listeners/jsonapi.rst
Missed the fact that this option accepts both booleans and arrays.
=> Fix description for withJsonApiVersion config option

docs/api.rst, docs/listeners.rst
This makes the JsonApiListener documentation find'able, there's no entry point atm.
=> Adds JsonApiListener to index and Api section

src/Listener/ApiPaginationListener.php, tests/TestCase/Listener/ApiPaginationListenerTest.php
Incorporates #499 + corrects a bad test using incorrect previous page. All jsonapi pagination tested successfully (1-of-3, 2-of-3, 3-of-3)
=> Fixes JSON API prev/next pagination

docs/listeners/custom.rst
Seems this example was implementing the Cake Event Interface, whereas elsewhere in the docs it says to extend the BaseListener, which is an abstract class with the `implementedEvents` method already in there.
=> Fixed incorrect class inheritance

src/Listener/ApiListener.php, tests/TestCase/Listener/ApiListenerTest.php
Since CakePHP 3.4 returns false for `_ext` as soon as `JsonApiListener` is loaded, all requests are treated as a JsonAPI request
=> Cake 3.4 returns false for _ext if not there

src/Listener/JsonApiListener.php, tests/App/Controller/CountriesController.php, tests/Fixture/CountriesFixture.php, tests/Fixture/CulturesFixture.php, tests/Fixture/CurrenciesFixture.php, tests/TestCase/Controller/JsonApiIntegrationTest.php
Status code after successfully created JSON API record should return 201 (now 200). http://jsonapi.org/format/#crud-creating-responses-201.
Closes #496
=> Return 201 for successfully created JSON API records

docs/listeners/jsonapi.rst, src/Listener/JsonApiListener.php, src/Schema/JsonApi/DynamicEntitySchema.php, src/View/JsonApiView.php, tests/App/Model/Entity/NationalCapital.php, tests/App/Model/Entity/NationalCity.php, tests/App/Model/Table/CountriesTable.php, tests/App/Model/Table/NationalCapitalsTable.php, tests/App/Model/Table/NationalCitiesTable.php, tests/Fixture/CountriesFixture.php, tests/Fixture/CulturesFixture.php, tests/Fixture/JsonApi/get_country_include_all_supported_associations.json, tests/Fixture/JsonApi/get_country_include_national-capital.json, tests/Fixture/JsonApi/get_country_include_national-capital_and_national-cities.json, tests/Fixture/JsonApi/get_country_include_national-cities.json, tests/Fixture/NationalCapitalsFixture.php, tests/Fixture/NationalCitiesFixture.php, tests/TestCase/Integration/JsonApi/DefaultAddActionIntegrationTest.php, tests/TestCase/Integration/JsonApi/IncludeQueryIntegrationTest.php, tests/TestCase/Integration/JsonApiBaseTestCase.php, tests/TestCase/Listener/JsonApiListenerTest.php, tests/TestCase/Schema/DynamicEntitySchemaTest.php, tests/TestCase/View/JsonApiViewTest.php
This dasherizes associations inside the `relationship` node. Closes #528.
~Not ready for merging, needs tests.~
=> Dasherize JSON API relationships node

docs/configuration.rst, src/Controller/Component/CrudComponent.php, tests/TestCase/Controller/Component/CrudComponentTest.php
With this change: https://github.com/cakephp/cakephp/pull/6906 one can have the AuthComponent working in `Controller::initialize` rather than `Controller::beforeFilter` - but if one does that with crud, the `dispatchComponents`property is not yet filled, and because of that the code in the ControllerTrait doesn't work. (https://github.com/FriendsOfCake/crud/blob/master/src/Controller/ControllerTrait.php#L96).
This makes the AuthComponent *skip* both authentication and authorization, unless there is boilerplate code as follows for each action (because of: https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/AuthComponent.php#L291)
```
<?php
namespace Controller;
use Cake\Event\Event;
class PostsController extends AppController
{
public function index()
{
return …
```
=> Move logic for dispatchComponents to ::initialize to comply with Cake 3.3 AuthComponent

docs/listeners/api.rst
this looks like a typo or perhaps a leftover from an older version of this plugin? There doesn't seem to be a JsonApiExceptionRenderer, and changing the reference to 'Crud\Error\ExceptionRenderer' produces the correct behavior as far as i can see.
=> documentation update: fix name of Exception Renderer class for use in Cake 3.3+

tests/TestCase/Error/ExceptionRendererTest.php
I've refactored some tests, using:
- `assertNotEmpty` instead of using `empty` PHP function.
=> Refactoring tests

src/Listener/ApiListener.php, tests/TestCase/Listener/ApiListenerTest.php
=> Ensure response's status code doesn't get set to null.

src/Listener/ApiPaginationListener.php, tests/TestCase/Listener/ApiPaginationListenerTest.php
After updating to crud tag 5.3.x the pagination failed due to a faulty replacement of the deprecated method InstanceConfigTrait::config(). 
At Crud\Listener\ApiPaginationListener line 71 the deprecated config method was used as a setter, but it was replaced as a getter.
=> ApiPaginationListener should use setConfig in beforeRender

src/Listener/RelatedModelsListener.php, tests/TestCase/Listener/RelatedModelsListenerTest.php
Noticed this deprecated calls when updating one of my apps
=> Remove deprecated calls from RelatedModelsListener

aliases.php
One of more could have been already aliased by other plugins like ADmad/Glide.
=> Check for each class individually.

src/Action/EditAction.php, src/Action/ViewAction.php, tests/TestCase/Listener/ApiListenerTest.php
The code in the docs throw exceptions
```php
$this->Crud->action()->serialize();
// Call to undefined method Crud\Action\ViewAction::serialize()
```
This PR fix that
=> Add SerializeTrait to View and Edit Actions

docs/actions/bulk.rst
A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
=> Remove unneeded apostrophe

docs/listeners/related-models.rst
Current example code breaks with an error. This fixes it.
=> Fix related-models.md example code

src/Action/IndexAction.php, tests/TestCase/Action/IndexActionTest.php
FriendsOfCake/crud-view#268 would retain the query string including page number. So if you were on last page with single record, redirecting back to same URL after record is deleted would cause paginator to throw `NotFoundException`.
=> Redirect to last page if requested page number doesn't exist.

src/Action/DeleteAction.php
Hello,
While upgrading my project to CakePHP 4, I discovered the DeleteAction does not implement the SerializeTrait, meaning you can't call `$this->Crud->action()->serialize(['my', 'keys'])` or anything like it. The documentation states you should be able to, so I figured it was just missing by accident and not by design, hence the PR.
=> Added the SerializeTrait to the DeleteAction

src/Controller/ControllerTrait.php
Controller action invocation has changed in CakePHP 4.2.
The ControllerFactory now reflects the action method for arguments injections.
This results in incorrect args to be passed as the factory generates args based on
CrudComponent::execute() reflection while we need the passed args from request.
=> Fixed passing of passed args to CrudComponent::execute().

phpstan.neon, psalm-baseline.xml, psalm.xml, src/Controller/ControllerTrait.php
This is to prevent the ControllerFactory from trying to type cast the method args.
It was just by dumb luck that this didn't cause problems earlier as we only have
actions with a single argument and 1st argument of CrudComponent::execute() is typed
as nullable string. Any custom action with non array 2nd argument would be broken.
=> Make ControllerTrait::isAction() return a dummy closure for mapped actions.

src/Controller/Component/CrudComponent.php, src/Controller/ControllerTrait.php, src/Core/ProxyTrait.php
The ControllerTrait::$mappedComponents usage was redundant as ProxyTrait::_crud()
always returned a CrudComponent instance.
=> Simplify Crud action execution.

src/Action/EditAction.php
Hi!
Currently _patch is mixed, so when an int is passed it will cause a type error, because _put is strongly typed.
Is this something that can be changed?
Cheers,
Frank
=> Added type to signature of _patch

src/Action/LookupAction.php, tests/TestCase/Action/LookupActionTest.php
Using the old "id" and "value" names could clash with search field names if using the Search plugin.
=> Use "keyField" and "valueField" query string vars for Lookup action.

src/Controller/Component/CrudComponent.php, src/Log/QueryLogger.php
Really simple PR, to restore the original workings of the query logger. In previous versions of crud, the query logger would not only store the query, but also the entire context, like the query execution time and rows affected. Right now, a cast to string means only the query is stored in the query log. This PR attempts to restore the original functionality, by using the jsonSerialize method for instances of LoggedQuery.
=> Fix query logger

psalm-baseline.xml, src/Controller/Component/CrudComponent.php
Normalize listeners and actions config in `setConfig()`.
=> Remove constructor overriding.

src/Error/ExceptionRenderer.php, src/Listener/ApiQueryLogListener.php, src/Traits/QueryLogTrait.php, tests/TestCase/Listener/ApiQueryLogListenerTest.php
=> Cleanup query logging code.
